# this script removes most of the output files generated by the tests

find . -name '*.dat' -exec rm '{}' \;

dirnames=("arg_dict_output.jl" "newmesh_linear" "mesh_complete" "output_init" "solution_done" "solution_error" "solution_ic" "solution_relfunc")

for dirname in "${dirnames[@]}";
do
  find . -name $dirname -type d -exec rm -r '{}' \;
done

# names with wildcards
find . -name 'solution_*' -type d -exec rm -r '{}' \;
find . -name 'checkpoint*' -type d -exec rm -r '{}' \;
find . -name '*~' -print -exec rm '{}' \;
find . -name 'input_vals_restart' -type l -print -exec rm '{}' \;
