# this user supplied file creates a dictionary of arguments
# if a key is repeated, the last use of the key is used
# it is a little bit dangerous letting the user run arbitrary code
# as part of the solver
# now that this file is read inside a function, it is better encapsulated

arg_dict = Dict{Any, Any} (
"var1" => 1,
"var2" => "a",
"var3" => 3.5,
"var4" => [1,2,3],
"var3" => 4,
"run_type" => 5,
"jac_type" => 2,
"order" => 1,
"use_DG" => true,
"Flux_name" => "LFFlus",
"IC_name" => "ICExp",
"SRCname" => "SRCExp",
"dimensions" => 3,
"variable_type" => :conservative,
#"variable_type" => :entropy,
#"IC_name" => "ICFile",
#"ICfname" => "start.dat",
#"Relfunc_name" => "ICRho1E2U3",
"numBC" => 1,
"BC1" => [ 0, 1, 2, 3, 4, 5],
"BC1_name" => "ExpBC",
#"BC2" => [4, 10],
#"BC2_name" => "noPenetrationBC",
#"BC2_name" => "isentropicVortexBC",
"delta_t" => 0.00005,
"t_max" => 500.000,
"smb_name" => "src/mesh_files/cube_benchmarksmall.smb",
#"dmg_name" => "/users/creanj/fasttmp/meshfiles/pcube3_1_.dmg",
"dmg_name" => ".null",
"res_abstol" => 1e-8,
"res_reltol" => 1e-20,
"step_tol" => 1e-10,
"itermax" => 20,
"output_freq" => 1,
"step_tol" => -1.0,
#"calc_error" => true,
#"calc_error_infname" => "solution_final.dat",
#"writeq" => true,
#"perturb_ic" => true,
#"perturb_mag" => 0.001,
#"write_sparsity" => true,
#"write_jac" => true,
#"write_edge_vertnums" => true,
#"write_face_vertnums" => true,
#"write_qic" => true,
#"writeboundary" => true,
#"write_res" => true,
"write_finalsolution" => true,
"write_finalresidual" => true,
"write_counts" => true,
"write_rhs" => false,
"do_postproc" => true,
"exact_soln_func" => "ICExp",
"solve" => true,
)
