arg_dict = Dict{Any, Any}(
"physics" => "Euler",
"run_type" => 5,
"jac_type" => 3,
"jac_method" => 2,
"newton_globalize_euler" => true,
"order" => 1,
"real_time" => false,
"variable_type" => :conservative,
"smb_name" => "SRCMESHES/2D_airfoil_np2.smb",
"dmg_name" => "SRCMESHES/2D_airfoil.dmg",
"IC_name" => "ICFreeStream",
"numBC" => 2,
"BC1" => [8],
"BC1_name" => "FreeStreamBC",
"BC2" => [5],
"BC2_name" => "noPenetrationBC",
"aoa" => -2.0, # -2.0,
"Ma" => 0.5,# default working = 0.3
"use_DG" => true,
"Flux_name" => "RoeFlux",
"operator_type" => "SBPOmega",
"exact_visualization" => true,
"t_max" => 500000.0,
"delta_t" => 0.0001,
"res_tol" => 1e-10,
"res_abstol" => 1e-10,
"res_reltol" => 1e-9,
"step_tol" => 1e-10,
"krylov_abstol" => 1e-16,
"krylov_reltol" => 1e-6,
"itermax" => 5000000000, # For RK4

# Integral contributions
"addVolumeIntegrals" => true,
"addFaceIntegrals" => true,
"addStabilization" => true,
"addBoundaryIntegrals" => true,

"writeq" => false,
"write_edge_vertnums" => false,
"write_face_vertnums" => false,
"write_qic" => false,
"writeboundary" => false,
"write_res" => false,
"print_cond" => false,
"write_counts" => false,
"write_vis" => false,
"output_freq" => 100000,
"solve" => true,
"do_postproc" => true,
"calc_functional" => false,

"objective_function" => "lift",
"geom_faces_objective" => [5],
"num_functionals" => 1,
"need_adjoint" => false, # Necessary for reverse mode

"exact_soln_func" => "ICFreeStream",
)
