arg_dict = Dict{Any, Any}(
"dimensions" => 2,
"use_DG" => true,
"operator_type" => "SBPOmega",
"run_type" => 1,
"real_time" => true,
"order" => 1,
"Flux_name" => "IRFlux",
"IC_name" => "ICPeriodicMMS",
"volume_integral_type" => 2,
"face_integral_type" => 2,
"Volume_flux_name" => "IRFlux",
"FaceElementIntegral_name" => "ESLW2FaceIntegral",
"vortex_x0" => 5.0,
"numBC" => 0,
"BC1_name" => "PeriodicMMSBC",
"CFL" => 0.25,
"t_max" => 10.0,
"SRCname" => "SRCPeriodicMMS",
"smb_name" => "SRCMESHES/square_curve.smb",
"dmg_name" => ".null",
"itermax" => 10000,
"output_freq" => 50,
"write_vis" => true,
"do_postproc" => true,
"exact_soln_func" => "ICPeriodicMMS",
"res_abstol" => 1e-8,
"res_reltol" => 1e-10,
"step_tol" => 1e-10,
"solve" => false,
)


