arg_dict = Dict{ASCIIString, Any}(
"dimension" => 2,
"use_DG" => true,
"operator_type" => "SBPOmega",
"run_type" => 1,
"real_time" => true,
"order" => 1,
"Flux_name" => "IRFlux",
"IC_name" => "ICUnsteadyVortex",
"volume_integral_type" => 2,
"face_integral_type" => 2,
"addFaceIntegrals" => true,
"addVolumeIntegrals" => true,
"Volume_flux_name" => "IRFlux",
"FaceElementIntegral_name" => "ECFaceIntegral",
"vortex_x0" => 5.0,
"numBC" => 0,
"delta_t" => 0.0005,
"t_max" => 0.50,
#"smb_name" => "unsteadyvortexp2_.smb",
#"dmg_name" => "unsteadyvortexp2_.dmg",
"smb_name" => "SRCMESHES/smallp4_.smb",
"dmg_name" => ".null",
"output_freq" => 50,
"write_vis" => false,
"do_postproc" => true,
"exact_soln_func" => "ICUnsteadyVortex",
"solve" => true,
"write_entropy" => true,
"write_entropy_freq" => 1,
)


