rm -v ./convergence.dat
rm -v ./solution_newton*vtu
rm -v ./solution_rk*vtu
rm -v ./jacobian*.dat
rm -v ./solution.dat
rm -v ./rhs*.dat
rm -v ./res0*.dat
rm -v ./IC*.dat
rm -v ./boundaryfaces*.txt
rm -v ./boundaryflux*.txt
rm -v ./SL0*.dat
rm -v ./SL*.dat
rm -v ./res*.dat
rm -v ./qic.dat
rm -v ./q*.dat
rm -v ./Fxi*.dat
rm -v ./eigs*.dat
rm -v ./boundary_nums.txt
rm -v ./res*.dat
rm -v ./dxidx.dat
rm -v ./coords.dat
rm -v ./boundaryf*.dat
rm -v ./Fxi.dat
rm -v ./edge_vertnusm.dat
rm -v ./face_vertnums.dat
rm -v ./boundary_nums.dat
rm -v ./sparsity_bnds.dat
rm -v ./counts*.txt
rm -v ./edge_vertdofs.txt
rm -v ./*vtu
rm -v ./coords_output.dat
rm -v ./functional_error*.dat
rm -v ./newton_solution*.dat
