# this user supplied file creates a dictionary of arguments
# if a key is repeated, the last use of the key is used
# it is a little bit dangerous letting the user run arbitrary code
# as part of the solver
# now that this file is read inside a function, it is better encapsulated

arg_dict = Dict{Any, Any} (
"run_type" => 1,
"jac_type" => 2,
"order" => 1,
"real_time" => false,
"t_max" => 1000.0,
"IC_name" => "ICp4",
"use_DG" => true,
"Flux_name" => "LFFlux",
"LFalpha" => 0,
"numBC" => 1,
"BC1" => [0, 1, 2, 3],
"BC1_name" => "p4BC",
"SRCname" => "SRCp4",
#"BC2" => [4, 10],
#"BC2_name" => "noPenetrationBC",
"delta_t" => 2*pi/5000,
#"smb_name" => "src/mesh_files/channel.smb",
#"smb_name" => "/users/creanj/test2/p1/m1/parallel2.smb",
#"dmg_name" => "parallel2.dmg",
"smb_name" => "src/mesh_files/psquare4.smb",
"dmg_name" => "src/mesh_files/psquare4.dmg",
#"smb_name" => "src/mesh_files/channel_verylarge.smb",
#"dmg_name" => "../../mesh_files/vortex.dmg",
"dmg_name" => ".null",
"res_tol" => 1e-10,
# "step_tol" => 1e-6,
"itermax" => 7000,
"res_abstol" => 1e-9,
#"res_reltol" => 1e-9,
#"step_tol" => 1e-10,
"writeq" => false,
"write_edge_vertnums" => false,
"write_face_vertnums" => false,
"write_qic" => false,
"writeboundary" => false,
"write_res" => false,
"print_cond" => false,
"write_counts" => false,
"write_vis" => true,
"output_freq" => 100,
"write_vis" => false,
"solve" => false,
"do_postproc" => true,
"exact_soln_func" => "ICp4",
)
